---
postgres_version:
  - 11

postgres_cluster:
  db01live:
    version: 11
    data: /var/lib/pgsql/10/db01live
    port: 5432
    #vip: 10.54.248.161
    stanza: db01live
    # keep 2 fullbackups
    backup_retention: 2
    role:
      test_ro:
    user:
      postgres:
        password: XXXX
      # replication:
      #   password: "{{pw_pgdb01_replication}}"
      #   options: replication
      nrpe:
        password: XXXAX
      test:
        password: XXXX
      user1:
        passsword: XXXX
      user2:
        password: XXXX
    #
    database:
      - name: test
        owner: test
        extension:
          - powa
    schema:
      - name: test
        db: test
        owner: test
    privs:
      - database: test
        schema: public
        target_roles: test
        type: default_privs
        roles: test_ro
        privs: select
        objs: tables
    membership:
      test_ro:
        members:
          - user1
          - user2
    hba:
      - contype: host
        users: nrpe
        source: samehost
        databases: postgres
        method: md5
      - contype: host
        users: nrpe
        source: samenet
        databases: postgres
        method: md5
      - contype: host
        users: postgres
        source: 0.0.0.0/0
        databases: all
        method: md5
    #
    settings:
      #shared_preload_libraries: powa,pg_stat_statements,pg_qualstats,pg_stat_kcache,hypopg
      archive_command: 'pgbackrest --stanza=db01live archive-push %p'
      shared_preload_libraries: powa,pg_stat_statements,pg_qualstats,pg_stat_kcache,hypopg
      wal_level: replica
      archive_mode: 'on'
      max_wal_senders: 10
      wal_keep_segments: 32
      max_replication_slots: 10
      hot_standby: 'on'
      # logging
      log_filename: 'postgresql-%Y-%m-%d.log'
      log_file_mode: '0644'
      log_rotation_age: 1d
      log_checkpoints: 'on'
      log_connections: 'on'
      log_disconnections: 'on'
      log_hostname: 'on'
      # Generated by PGConfig 2.0 beta
      ## http://pgconfig.org
      # https://www.pgconfig.org/#/tuning?total_ram=1&max_connections=30&environment_name=Desktop&pg_version=9.6&os_type=Linux&arch=x86-64&drive_type=SSD&share_link=true
      # Memory Configuration
      shared_buffers: 64MB
      effective_cache_size: 256MB
      work_mem: 6MB
      maintenance_work_mem: 64MB
      # Checkpoint Related Configuration
      min_wal_size: 2GB
      max_wal_size: 1GB
      checkpoint_completion_target: 0.5
      wal_buffers: 2MB
      # Network Related Configuration
      listen_addresses: '*'
      max_connections: 30
      # Hard Drive Configuration
      random_page_cost: 1.1
      effective_io_concurrency: 200




## Logging configuration for pgbadger
#logging_collector = on
#log_checkpoints = on
#log_connections = on
#log_disconnections = on
#log_lock_waits = on
#log_temp_files = 0
#lc_messages = 'C'
#
## Adjust the minimum time to collect data
#log_min_duration_statement = '10s'
#log_autovacuum_min_duration = 0
#
## 'stderr' format configuration
#log_destination = 'stderr'
#log_line_prefix = '%t [%p]: [%l-1] user=%u,db=%d,app=%a,client=%h '
